services:
    es_base.twig.extension.google_analytics:
        class: ES\Bundle\BaseBundle\Twig\Extension\GoogleAnalyticsExtension
        arguments:
            - @service_container
            - %es_base.google_analytics.website_name%
            - %es_base.google_analytics.trackers%
            - %es_base.host_env%
            - %es_base.google_analytics.tracked_environments%
        tags:
            - { name: twig.extension }
