services:
    es_base.twig.extension.cameleon:
        public: false
        class: ES\Bundle\BaseBundle\Twig\Extension\BaseExtension
        arguments:
            - @service_container
            - %es_base.templating.bootstrap.use_cdn%
        tags:
            - { name: twig.extension, alias: es_base }
