
services:

    es_base.security.entry_point.form:
        class: %security.authentication.form_entry_point.class%
        arguments:
            - @http_kernel
            - @security.http_utils
            - %es_base.security.login_path%

    es_base.security.context_listener:
        class: %security.context_listener.class%
        arguments:
            - @es_base.security.context
            - [ @es_base.security.user_provider.users ]
            - %es_base.security.provider_key%
            - @logger
            - @event_dispatcher
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: handle, priority: 102 }
            - { name: monolog.logger, channel: cameleon_security }

    es_base.security.listener.form:
        class: %security.authentication.listener.form.class%
        arguments:
            - @es_base.security.context
            - @es_base.security.authentication.manager
            - @security.authentication.session_strategy
            - @security.http_utils
            - %es_base.security.provider_key%
            - @es_base.security.authentication.success_handler
            - @es_base.security.authentication.failure_handler
            - %es_base.security.options%
            - @logger
            - @event_dispatcher
            - @security.csrf.token_manager
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: handle, priority: 101 }
            - { name: monolog.logger, channel: cameleon_security }

    es_base.security.authentication.success_handler:
        class: %security.authentication.success_handler.class%
        arguments:
            - @security.http_utils
            - { login_path: /staging/login, check_path: /staging/login_check }
    es_base.security.authentication.failure_handler:
        class: %security.authentication.failure_handler.class%
        arguments:
            - @http_kernel
            - @security.http_utils
            - %es_base.security.options%
            - @logger
        tags:
            - { name: monolog.logger, channel: cameleon_security }
